In [1]:
!pip install --quiet tensorflow-text
# Clone the entire repo.
%cd /content/
!rm -r -f dl4tm
!git clone git://github.com/Jeilef/DL4TM_Text2Python.git dl4tm
%cd dl4tm
!ls

/content
Cloning into 'dl4tm'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 73 (delta 33), reused 39 (delta 13), pack-reused 0
Receiving objects: 100% (73/73), 387.18 KiB | 6.91 MiB/s, done.
Resolving deltas: 100% (33/33), done.
/content/dl4tm
conala-corpus-v1.1  README.md	      text2python.ipynb  transformer_util.py
google.ipynb	    requirements.txt  transformer.ipynb


In [2]:
import numpy as np
import json
import logging
from tokenize import tokenize
from io import BytesIO
import tensorflow_hub as hub
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow_text # See https://github.com/tensorflow/hub/issues/463

In [3]:
logging.getLogger('tensorflow').setLevel(logging.ERROR)  # suppress warnings

In [4]:
train_file = open("conala-corpus-v1.1/conala-corpus/conala-train.json", "r")
train_json = json.load(train_file)

print(len(train_json))
print(train_json[0])

2379
{'intent': 'How to convert a list of multiple integers into a single integer?', 'rewritten_intent': "Concatenate elements of a list 'x' of multiple integers to a single integer", 'snippet': 'sum(d * 10 ** i for i, d in enumerate(x[::-1]))', 'question_id': 41067960}


In [5]:
base_sentences = [item["rewritten_intent"] for item in train_json]
codes = [item["snippet"] for item in train_json]

print(base_sentences[0])
print(codes[0])

Concatenate elements of a list 'x' of multiple integers to a single integer
sum(d * 10 ** i for i, d in enumerate(x[::-1]))


In [6]:
# Use custom tokenize function for code snippets
def tokenize_python(s):
    tokenized = tokenize(BytesIO(s.numpy()).readline)
    tokens = [token[1] for token in tokenized]
    tensor = tf.convert_to_tensor(tokens, dtype=tf.string)
    
    return tensor

example = tf.constant(codes[0])
tokenize_python(example)

<tf.Tensor: shape=(26,), dtype=string, numpy=
array([b'utf-8', b'sum', b'(', b'd', b'*', b'10', b'**', b'i', b'for',
       b'i', b',', b'd', b'in', b'enumerate', b'(', b'x', b'[', b':',
       b':', b'-', b'1', b']', b')', b')', b'', b''], dtype=object)>

In [7]:
data = tf.data.Dataset.from_tensor_slices(codes)
data = data.map(lambda x : tf.py_function(func=tokenize_python, inp=[x], Tout=tf.string))

code_chars = set()
sentence_chars = set()
for tokens in data:
  for c in tokens:
    code_chars.add(c.numpy())

for tokens in base_sentences:
  if tokens != None:
    for c in tokens:
      sentence_chars.add(c)

code_chars = sorted(list(code_chars))
sentence_chars = sorted(list(sentence_chars))
code_idx_to_char = {}
code_char_to_idx = {}
sentence_idx_to_char = {}
sentence_char_to_idx = {}
for idx, cc in enumerate(code_chars):
  code_idx_to_char[idx] = cc
  code_char_to_idx[cc] = idx

for idx, cc in enumerate(sentence_chars):
  sentence_idx_to_char[idx] = cc
  sentence_char_to_idx[cc] = idx

max_code_len = max([len(line) for line in codes])

print(len(code_chars), max_code_len, len(codes))

2839 232 2379


In [10]:
tokenized_sentences = np.zeros(shape=(len(base_sentences), max_code_len, len(sentence_chars)), dtype="int8")

tokenized_codes = np.zeros(shape=(len(codes), max_code_len, len(code_chars)), dtype="int8")
targets = np.zeros(shape=(len(codes), max_code_len, len(code_chars)), dtype="int8")
data_numpy_iterator = list(data.as_numpy_iterator())

for i in range(len(data)):
  if i % 100 == 0:
    print(f"Finished {i/len(data) * 100} %")
  if base_sentences[i] == None:
    continue
  for k, ch in enumerate(base_sentences[i]):
    tokenized_sentences[i, k, sentence_char_to_idx[ch]] = 1
  for k, ch in enumerate(data_numpy_iterator[i]):
    tokenized_codes[i, k, code_char_to_idx[ch]] = 1
    if k > 0:
      targets[i, k, code_char_to_idx[ch]] = 1

Finished 0.0 %
Finished 4.203446826397647 %
Finished 8.406893652795294 %
Finished 12.610340479192939 %
Finished 16.813787305590587 %
Finished 21.01723413198823 %
Finished 25.220680958385877 %
Finished 29.424127784783522 %
Finished 33.627574611181174 %
Finished 37.83102143757881 %
Finished 42.03446826397646 %
Finished 46.2379150903741 %
Finished 50.441361916771754 %
Finished 54.644808743169406 %
Finished 58.848255569567044 %
Finished 63.051702395964696 %
Finished 67.25514922236235 %
Finished 71.45859604875999 %
Finished 75.66204287515762 %
Finished 79.86548970155528 %
Finished 84.06893652795291 %
Finished 88.27238335435057 %
Finished 92.4758301807482 %
Finished 96.67927700714586 %


In [11]:
# Pretrained BERT encoder
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
preprocessor = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
encoder_inputs = preprocessor(text_input)
encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1", trainable=True)
outputs = encoder(encoder_inputs)
pooled_output = outputs["pooled_output"]      # [batch_size, 128].
sequence_output = outputs["sequence_output"]  # [batch_size, seq_length, 128].

In [12]:
# Transformer Decoder  taken from https://www.tensorflow.org/tutorials/text/transformer
from transformer_util import Decoder
output_tokens = 8000
sample_decoder = Decoder(num_layers=2, d_model=128, num_heads=2,
                         dff=128, target_vocab_size=output_tokens,
                         maximum_position_encoding=5000)

decoder_input = tf.keras.layers.Input(shape=(None, ), dtype=tf.string)

vectorize_layer = keras.layers.experimental.preprocessing.StringLookup(max_tokens=output_tokens)
vectorize_layer.adapt(data)

vectorized_input = vectorize_layer(decoder_input)

decoder_output, attn = sample_decoder(vectorized_input,
                              enc_output=sequence_output,
                              training=False,
                              look_ahead_mask=None,
                              padding_mask=None)
final_layer = tf.keras.layers.Dense(output_tokens)
output = final_layer(decoder_output)


embedding_model = tf.keras.Model((text_input, decoder_input), output)

In [13]:
sentence = tf.constant([train_json[0]["rewritten_intent"]])
snippet = tf.constant(train_json[0]["snippet"])
snippet = tf.py_function(func=tokenize_python, inp=[snippet], Tout=tf.string)
snippet = tf.expand_dims(snippet, axis=0)
print(sentence.shape, snippet.shape)
result = embedding_model((sentence, snippet))
result

(1,) (1, 26)


<tf.Tensor: shape=(1, 26, 8000), dtype=float32, numpy=
array([[[ 0.25900948,  0.05902249,  0.00255737, ..., -0.14142132,
          0.060927  ,  0.23605488],
        [ 0.2641915 ,  0.04997048,  0.11746741, ..., -0.11563613,
          0.0299585 ,  0.2452411 ],
        [ 0.22051044, -0.03371699,  0.07480508, ..., -0.12167043,
          0.09683892,  0.18546578],
        ...,
        [ 0.21927257, -0.07914125,  0.10151628, ..., -0.08671107,
          0.06166898,  0.28820792],
        [ 0.1649797 , -0.09419025,  0.05277481, ..., -0.0641139 ,
          0.06363688,  0.22325364],
        [ 0.16321684, -0.08993292,  0.04195784, ..., -0.05346364,
          0.04414991,  0.2221666 ]]], dtype=float32)>

In [14]:
# TODO: Preprocess code samples
# TODO: Set up masking
# TODO: Run training

In [15]:
embedding_model.compile(optimizer="adam", loss="categorical_crossentropy")
embedding_model.fit(x=[tokenized_sentences, tokenized_codes], y=[targets], batch_size=16)

ValueError: ignored